config/routes.rb
Rails.application.routes.draw do
  root to: "records#index"

  resources :records 

end

app/models/record.rb
class Record < ActiveRecord::Base
    class << self
      attr_reader :column_names
    end
  @column_names = []

    ("a".."r").each do |letter|
      @column_names << (letter + "cell")
    end


  def self.import(file)
    spreadsheet = Roo::Excelx.new(file.path, nil, :ignore)

    (1..spreadsheet.last_row).each do |i|

      row = Hash.new
      ("a".."r").each_with_index do |letter,index|

        row[@column_names[index]] = spreadsheet.row(i)[index]
      end

      record = Record.new(row)
      record.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def index
    @records = Record.paginate(:page => params[:page])
  end

  def new
    @record = Record.new
  end

  def create

    Record.import(params[:file]) rescue flash[:notice] = "error importing"
    flash[:notice] ||= "spreadsheet imported"

    redirect_to records_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myparser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
  <%= flash[:notice] %>
</p>
<%= yield %>

</body>
</html>

app/views/records/index.html.erb
<h1>Records</h1>
<%= link_to "New record", new_record_path %>

<table>
  <tr>
<% for cn in Record.column_names %>
  <th> <%= cn %> </th>
  <% end %>
  </tr>
<% for record in @records do %>
  <tr>

<% for sell_method in Record.column_names %>
  <td> <%= record.send(sell_method)%> </td>
<% end %>

  </tr>
<% end %>
</table>

<p></p>


<%= will_paginate @records %>

app/views/records/new.html.erb
<h2>Import xls</h2>


<%= form_tag records_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>